### PR TITLE
Fix 32-bit build issues

### LINKED ISSUE #232: Compiling v3.0.0 fails on x86
Tried to integrate the 3.0.0 release into vcpkg, but it fails due to:

```
2>C:\dev\libE57Format\src\CheckedFile.cpp(324,42): error C2220: the following warning is treated as an error
2>C:\dev\libE57Format\src\CheckedFile.cpp(324,42): warning C4244: 'argument': conversion from 'uint64_t' to 'size_t', possible loss of data
2>C:\dev\libE57Format\src\CheckedFile.cpp(334,45): warning C4244: 'argument': conversion from 'uint64_t' to 'size_t', possible loss of data
``` 

Sadly warnings as errors will be always enabled by default as `E57_BUILDING_SELF` will be set to `ON`.

### PR DESCRIPTION
**Pull request by asmaloney**
- I haven't got the 32-bit CI to build properly because of xerces-c link problems.
- I realize that the 32-bit check I have in `ReaderImpl.cpp` will ~~silently~~ drop points if there are more than `4,294,967,295` in a single scan and output a warning to the console. This seems unlikely (impossible?). There is no mechanism to return partial success, so instead of throwing an exception I decided to just drop them since it's such an extreme edge case.

Fixes #232

### CODE REVIEW

File: src/ReaderImpl.cpp [hunk 1]
```diff
@@ -627,7 +627,20 @@ namespace e57
...
+#ifdef E57_32_BIT
+      // If we exceed the size_t max, only process the max (4,294,967,295 points).
+      if ( points.childCount() > static_cast<int64_t>( std::numeric_limits<size_t>::max() ) )
+      {
+         data3DHeader.pointCount = static_cast<int64_t>( std::numeric_limits<size_t>::max() );
+      }
+      else
+      {
+         data3DHeader.pointCount = static_cast<size_t>( points.childCount() );
+      }
```
Comment (SunBlack) [inline src/ReaderImpl.cpp:640]: Doesn't this throw a warning as one time you assign a signed type (`int64_t`) to `pointCount` and one time a unsigned type (`size_t`)?

I don't see the type of `pointCount` here, but you can simplify the code to sth like this:
```suggestion
      data3DHeader.pointCount = std::min<int64_t>( points.childCount(), std::numeric_limits<size_t>::max() );
```
As `int64_t` is passed as template parameter, both parameter will be cast implicit to this type.

**Review by SunBlack — CHANGES_REQUESTED** [review]

**Comment by SunBlack** [comment]
> * I realize that the 32-bit check I have in `ReaderImpl.cpp` will silently drop points if there are more than `4,294,967,295` in a single scan. This seems unlikely (impossible?). There is no mechanism to return partial success, so instead of throwing an exception I decided to just drop them since it's such an extreme edge case.

Is it possible to throw a warning somehow? Or you could set a flag (as I'm not using your API, just another of my team, I don't know how the API is currently designed).

File: src/ReaderImpl.cpp (hunk 1 above)
Comment (asmaloney) [reply src/ReaderImpl.cpp]: Yeah - that second cast is incorrect. `data3DHeader.pointCount` is `size_t`. This is a unsigned-to-signed conversion (to size_t), so I don't think std::min can be used here.

I added some output here (see below) so I need the "if" anyways.

**Comment by asmaloney** [comment]
> Is it possible to throw a warning somehow?

Unfortunately this is an API I inherited and it doesn't have warnings or flags of any kind - I can throw an exception, I can just return false, or I can process as much as possible. I could add a flag system, but I don't think I want to get into that right now. In the meantime I output a warning to the console if we are truncating.

I think the error handling could use a look - like why does`ReaderImpl::ReadData3D` function just return false on invalid parameters? But this isn't something I'm going to tackle now - maybe for 4.0 if there's any interest in/contributions to v3.0.

I'm also not really that keen on spending a whole bunch of time on 32-bit to be honest. Do you think anyone will be trying to deal with > 4,294,967,295 points in one scan (especially anyone building this as 32-bit)? (I don't think I've compiled anything for 32-bit in over a decade.)

**Comment by SunBlack** [comment]
> > Is it possible to throw a warning somehow?
> 
> Unfortunately this is an API I inherited and it doesn't have warnings or flags of any kind - I can throw an exception, I can just return false, or I can process as much as possible. I could add a flag system, but I don't think I want to get into that right now. In the meantime I output a warning to the console if we are truncating.

Indeed, a hint on the console is enough. It is only about the fact that you can somehow notice that truncation has taken effect there.

> I'm also not really that keen on spending a whole bunch of time on 32-bit to be honest. Do you think anyone will be trying to deal with > 4,294,967,295 points in one scan (especially anyone building this as 32-bit)? (I don't think I've compiled anything for 32-bit in over a decade.)

We have some point clouds with more points, but they were also just composed of several tiles. From there: Yup, unlikely that you get such large E57 files - and if then, unlikely that you work only with 32-bit system.

**Comment by asmaloney** [comment]
E57 allows `N` (where N is "zero or more") scans in each file, so as long as they are each < 4,294,967,295 points (on 32-bit build) we should be fine. They can always avoid using this "Simple API" and use the full API directly if that's a problem. Anyone trying to process that much data on a 32-bit build... needs to invest in new hardware/software. 😆

Thanks @SunBlack.
