### PR TITLE
E57XmlParser: Parse doubles in a local-independent way

### LINKED ISSUE #172: Floating point number parsing is affected by the locale
If I have a program using this library while having the locale set to a language using for example commas as the decimal separator, the numbers are parsed incorrectly.

For example, `8.123e-2` becomes simply `8`.

### PR DESCRIPTION
**Pull request by Hugal31**
Use std::istringstream with `imbue(std::locale::classic())` to parse doubles to avoid locale related problem when parsing text floats.

I could have also done it for convertStrToLL, but I am not aware of locale-related issue with integers.

Fixes #172

### CODE REVIEW

File: src/E57XmlParser.cpp [hunk 1]
```diff
@@ -83,6 +85,17 @@ inline int64_t convertStrToLL( const std::string &inStr )
 #endif
 }
 
+/// Parse a double according the the classic ("C") locale.
+/// \return The parsed double or 0.0 on error.
+inline double convertStrToDouble( const std::string &inStr )
```
Comment (asmaloney) [inline src/E57XmlParser.cpp:90]: Could you please move this to StringFunctions and rename to `strToDouble` to parallel `floatingPointToStr`? You can keep it inline if you want.

Also the docs are generally using `@return` instead of `\return`.

**Review by asmaloney — CHANGES_REQUESTED** [review]

**Review by asmaloney — APPROVED** [review]
Awesome - thanks!
